### ISSUE TITLE
The guide is offline

### ISSUE THREAD

**Issue by larsschellhas** [Juni4567/Slick-photoswipe#1]
Since there hasn't been much activitiy on this repo and the website is not available, I was wondering whether this project is still alive and working?

**Comment by Juni4567** [comment]
Hi thank you. Yes it's still alive. Here is an alternative link https://juni4567.github.io/slick-photoswipe/

**Comment by larsschellhas** [comment]
Thanls for the quick response! 👍 
Do you have the step-by-step guide anywhere, too? :D

**Comment by Juni4567** [comment]
Sorry the hosting has expired. I'll update the link tonight
